# Set OS to linux
os: linux
dist: xenial

matrix:
  - language: cpp
    compiler:
      - g++
    addons:
      apt:
        packages:
        - gcc-4.8
        - g++-4.8
        - build-essential
        - cmake
        - libopencv-dev

  - language: python
    python: 3.6
    install:
      - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8 -std=c++11 -DENABLE_REINFORCEMENT_LEARNING" CC="gcc-4.8"; fi
      # Install python dependencies
      - sudo apt-get install python
      - python -m pip install numpy opencv-python
    script:
      - bash explorer.sh
      - python main.py 50,30 150,150 3,1