# Set OS to linux
os: linux

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.5

before_install:
  - sudo apt-get update

# Install the library dependencies
install:
  - pip3 install numpy

# Run python scripts
script:
  - bash explorer.sh
  - python3 main.py 3,1