# Set OS to linux
os: linux
dist: bionic

language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3.6

install:
  - pip3 install numpy opencv-python
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libopencv-dev

script:
  - bash explorer.sh
  - python main.py 50,30 150,150 3,1